// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_ac_stats
Rcpp::NumericVector rcpp_ac_stats(Rcpp::NumericVector z, Rcpp::List nbs, Rcpp::List wts, std::string ac_type);
RcppExport SEXP hotspotr_rcpp_ac_stats(SEXP zSEXP, SEXP nbsSEXP, SEXP wtsSEXP, SEXP ac_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nbs(nbsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type wts(wtsSEXP);
    Rcpp::traits::input_parameter< std::string >::type ac_type(ac_typeSEXP);
    __result = Rcpp::wrap(rcpp_ac_stats(z, nbs, wts, ac_type));
    return __result;
END_RCPP
}
// rcpp_get_neighbours
Rcpp::List rcpp_get_neighbours(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP hotspotr_rcpp_get_neighbours(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(rcpp_get_neighbours(x, y));
    return __result;
END_RCPP
}
// rcpp_ives
Rcpp::NumericVector rcpp_ives(Rcpp::List nbs, int nt, double alpha_t, double alpha_s, Rcpp::NumericVector svec, Rcpp::NumericVector rvec);
RcppExport SEXP hotspotr_rcpp_ives(SEXP nbsSEXP, SEXP ntSEXP, SEXP alpha_tSEXP, SEXP alpha_sSEXP, SEXP svecSEXP, SEXP rvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type nbs(nbsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_t(alpha_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_s(alpha_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type svec(svecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rvec(rvecSEXP);
    __result = Rcpp::wrap(rcpp_ives(nbs, nt, alpha_t, alpha_s, svec, rvec));
    return __result;
END_RCPP
}
// rcpp_ives_spatial
Rcpp::NumericVector rcpp_ives_spatial(Rcpp::List nbs, int nt, double alpha_t, double alpha_s, Rcpp::NumericVector svec, Rcpp::NumericVector rvec);
RcppExport SEXP hotspotr_rcpp_ives_spatial(SEXP nbsSEXP, SEXP ntSEXP, SEXP alpha_tSEXP, SEXP alpha_sSEXP, SEXP svecSEXP, SEXP rvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type nbs(nbsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_t(alpha_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_s(alpha_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type svec(svecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rvec(rvecSEXP);
    __result = Rcpp::wrap(rcpp_ives_spatial(nbs, nt, alpha_t, alpha_s, svec, rvec));
    return __result;
END_RCPP
}
// rcpp_trunc_ndist
Rcpp::NumericVector rcpp_trunc_ndist(int len, double sd);
RcppExport SEXP hotspotr_rcpp_trunc_ndist(SEXP lenSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    __result = Rcpp::wrap(rcpp_trunc_ndist(len, sd));
    return __result;
END_RCPP
}
// rcpp_neutral_hotspots
Rcpp::NumericVector rcpp_neutral_hotspots(Rcpp::List nbs, Rcpp::List wts, Rcpp::List nbsi, double alpha, double sd0, bool log_scale, int niters, std::string ac_type);
RcppExport SEXP hotspotr_rcpp_neutral_hotspots(SEXP nbsSEXP, SEXP wtsSEXP, SEXP nbsiSEXP, SEXP alphaSEXP, SEXP sd0SEXP, SEXP log_scaleSEXP, SEXP nitersSEXP, SEXP ac_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type nbs(nbsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type wts(wtsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nbsi(nbsiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sd0(sd0SEXP);
    Rcpp::traits::input_parameter< bool >::type log_scale(log_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type niters(nitersSEXP);
    Rcpp::traits::input_parameter< std::string >::type ac_type(ac_typeSEXP);
    __result = Rcpp::wrap(rcpp_neutral_hotspots(nbs, wts, nbsi, alpha, sd0, log_scale, niters, ac_type));
    return __result;
END_RCPP
}
// rcpp_neutral_hotspots_ntests
Rcpp::NumericMatrix rcpp_neutral_hotspots_ntests(Rcpp::List nbs, Rcpp::List wts, Rcpp::List nbsi, double alpha, double sd0, int niters, std::string ac_type, bool log_scale, int ntests);
RcppExport SEXP hotspotr_rcpp_neutral_hotspots_ntests(SEXP nbsSEXP, SEXP wtsSEXP, SEXP nbsiSEXP, SEXP alphaSEXP, SEXP sd0SEXP, SEXP nitersSEXP, SEXP ac_typeSEXP, SEXP log_scaleSEXP, SEXP ntestsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type nbs(nbsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type wts(wtsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nbsi(nbsiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sd0(sd0SEXP);
    Rcpp::traits::input_parameter< int >::type niters(nitersSEXP);
    Rcpp::traits::input_parameter< std::string >::type ac_type(ac_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type log_scale(log_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type ntests(ntestsSEXP);
    __result = Rcpp::wrap(rcpp_neutral_hotspots_ntests(nbs, wts, nbsi, alpha, sd0, niters, ac_type, log_scale, ntests));
    return __result;
END_RCPP
}
