#' getisord
#'
#' Calculates the Getis-Ord statistic for spatial association between 5
#' rectangular neighbouring points on a regular grid
#'
#' @param z0 Square data matrix
#'
#' @return A sorted vector of values of the Getis-Ord statistic re-scaled
#' between 0 and 1
#'
#' @seealso \code{morani}, \code{morani}
#'
#' @export
getis_ord <- function (z0)
{
    # Comparison of Getis-Ord G calculated from spdep vs calculated directly.
    # The observed difference must somehow arise from how spdep calculates
    # neighbours? Whatever the reason, the direct calculation is an exact
    # implementation of the statistic, and is much simpler, so can be used to
    # compare with data generated by Ives2D
    size <- dim (z0) [1]
    #xycoords <- cbind (rep (seq (size), each=size), rep (seq (size), size))
    #nbs <- spdep::cell2nb (size, size, type='rook', torus=TRUE)
    #nbs <- spdep::nb2listw (nbs, style='B')
    #G0 <- spdep::localG (as.vector (z0), nbs)

    z <- rbind (z0, z0, z0)
    z <- cbind (z, z, z)
    indx <- size + seq (size)
    xmn <- mean (z0)
    S <- sum (z0 ^ 2) / length (z0)
    wx <- (z [indx-1,indx] + z [indx+1,indx] + z [indx,indx-1] +
           z [indx,indx+1] + z [indx,indx]) / 5
    denom <- sqrt ((size * 5 * 0.2 ^ 2 - 1) / (size - 1))
    wx <- (wx - xmn) / (S * denom)
    sort ((wx - min (wx)) / diff (range (wx)), decreasing=TRUE)
}
