# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_ac_stats
#'
#' Computes spatial autocorrelation statistics for a given input matrix
#'
#' @param nbs An \code{spdep} \code{nb} object listing all neighbours of each
#' point
#' @param x Corresponding vector of values
#' @param ac_type Character string specifying type of aucorrelation
#' (\code{moran}, \code{geary}, or code{getis-ord}).
#'
#' @return A vector of sorted spatial autocorrelation statistics scaled between
#' zero and one.
#'
rcpp_ac_stats <- function(nbs, x, ac_type) {
    .Call('hotspotr_rcpp_ac_stats', PACKAGE = 'hotspotr', nbs, x, ac_type)
}

#' rcpp_get_neighbours
#'
#' Determines neighbours of points (x, y) using Delaunay triangulation
#'
#' @param x Vector of x-coordinates
#' @param y Vector of y-coordinates
#'
#' @return List of neighbours
#'
rcpp_get_neighbours <- function(x, y) {
    .Call('hotspotr_rcpp_get_neighbours', PACKAGE = 'hotspotr', x, y)
}

#' rcpp_ives2d
#'
#' Implements neutral model of Ives & Klopfer (Ecology 1997).
#'
#' @param nbs An \code{spdep} \code{nb} object listing all neighbours of each
#' point. 
#' @param alpha_t Strength of temporal autocorrelation
#' @param alpha_s Strength of spatial autocorrelation
#' @param nt Number of successive layers of temporal and spatial autocorrelation
#' used to generate final modelled values
#' @param svec Vector of random numbers for values of \code{s} drawn from a
#' truncated normal ' distribution.
#' @param rvec Vector of random numbers for values of \code{r} drawn from a
#' truncated normal ' distribution.
#'
#' @return A vector of simulated values of same size as \code{nbs}.
#'
rcpp_ives2d <- function(nbs, nt, alpha_t, alpha_s, svec, rvec) {
    .Call('hotspotr_rcpp_ives2d', PACKAGE = 'hotspotr', nbs, nt, alpha_t, alpha_s, svec, rvec)
}

#' rcpp_ives2d_space
#'
#' Implements neutral model of Ives & Klopfer (Ecology 1997) with additional
#' spatial ' structure, implented here through replacing generic local
#' autocorrelation ' with movement along maximal local gradients.
#'
#' @param nbs An \code{spdep} \code{nb} object listing all neighbours of each
#' point. 
#' @param alpha_t Strength of temporal autocorrelation
#' @param alpha_s Strength of spatial autocorrelation
#' @param nt Number of successive layers of temporal and spatial autocorrelation
#' used to generate final modelled values
#' @param svec Vector of random numbers for values of \code{s} drawn from a
#' truncated normal ' distribution.
#' @param rvec Vector of random numbers for values of \code{r} drawn from a
#' truncated normal ' distribution.
#'
#' @return A vector of simulated values of same size as \code{nbs}.
#'
rcpp_ives2d_space <- function(nbs, nt, alpha_t, alpha_s, svec, rvec) {
    .Call('hotspotr_rcpp_ives2d_space', PACKAGE = 'hotspotr', nbs, nt, alpha_t, alpha_s, svec, rvec)
}

#' rcpp_neutral2d
#'
#' Implements neutral model in two dimensions
#'
#' @param nbs An \code{spdep} \code{nb} object listing all neighbours of each
#' point. 
#' @param alpha_t Strength of temporal autocorrelation
#' @param alpha_s Strength of spatial autocorrelation
#' @param sd0 Standard deviation of truncated normal distribution used to model
#' environmental variation (with mean of 1)
#' @param nt Number of successive layers of temporal and spatial autocorrelation
#' used to generate final modelled values
#'
#' @return A vector of simulated values of same size as \code{nbs}.
#'
rcpp_neutral2d <- function(nbs, alpha_t, alpha_s, sd0, nt) {
    .Call('hotspotr_rcpp_neutral2d', PACKAGE = 'hotspotr', nbs, alpha_t, alpha_s, sd0, nt)
}

#' rcpp_neutral2d_ntests
#'
#' Performs repeated neutral tests to yield average distributions of both
#' hotspot values and spatial autocorrelation statistics.
#'
#' @param nbs An \code{spdep} \code{nb} object listing all neighbours of each
#' point. 
#' @param alpha_t Strength of temporal autocorrelation
#' @param alpha_s Strength of spatial autocorrelation
#' @param sd0 Standard deviation of truncated normal distribution used to model
#' environmental variation (with mean of 1)
#' @param nt Number of successive layers of temporal and spatial autocorrelation
#' used to generate final modelled values
#' @param ntests Number of tests used to obtain average values
#' @param ac_type Character string specifying type of aucorrelation
#' (\code{moran}, \code{geary}, or code{getis-ord}).
#'
#' @return A matrix of dimension (size, 2), with first column containing
#' sorted and re-scaled hotspot values, and second column containing sorted and
#' re-scaled spatial autocorrelation statistics.
#'
rcpp_neutral2d_ntests <- function(nbs, alpha_t, alpha_s, sd0, nt, ntests, ac_type) {
    .Call('hotspotr_rcpp_neutral2d_ntests', PACKAGE = 'hotspotr', nbs, alpha_t, alpha_s, sd0, nt, ntests, ac_type)
}

