# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_ives2d <- function(size, nt, alpha_t, alpha_s, svec, rvec) {
    .Call('hotspotr_rcpp_ives2d', PACKAGE = 'hotspotr', size, nt, alpha_t, alpha_s, svec, rvec)
}

rcpp_neutral1d <- function(size, alpha_t, alpha_s, nt, eps) {
    .Call('hotspotr_rcpp_neutral1d', PACKAGE = 'hotspotr', size, alpha_t, alpha_s, nt, eps)
}

rcpp_neutral2d_1test <- function(size, alpha_t, alpha_s, sd0, nt) {
    .Call('hotspotr_rcpp_neutral2d_1test', PACKAGE = 'hotspotr', size, alpha_t, alpha_s, sd0, nt)
}

rcpp_ac_stats <- function(x, ac_type) {
    .Call('hotspotr_rcpp_ac_stats', PACKAGE = 'hotspotr', x, ac_type)
}

rcpp_morani <- function(x) {
    .Call('hotspotr_rcpp_morani', PACKAGE = 'hotspotr', x)
}

rcpp_neutral2d_ntests <- function(size, alpha_t, alpha_s, sd0, nt, ntests, ac_type) {
    .Call('hotspotr_rcpp_neutral2d_ntests', PACKAGE = 'hotspotr', size, alpha_t, alpha_s, sd0, nt, ntests, ac_type)
}

