#' run_tests
#'
#' Tests observed data (\code{ymat}) against a series of neutral models
#'
#' @param size Size of the square grid on which to generate model. Total number
#' of points is size ^ 2. (Has no effect if \code{ymat} is given, in which case
#' value is determined by its dimensions)
#' @param alpha Vector of two components providing starting values for the
#' strength of autocorrelation in time and space
#' @param nt Number of successive layers of temporal and spatial autocorrelation
#' used to generate test field
#' @param ntests Number of tests to run, with statistics calculated from the
#' mean of \code{ntests}
#' @param neutral If TRUE, uses a neutral field for the tests rather than a
#' structured field generated by \code{ives2D}
#' @param actype type of autocorrelation statistic to use in tests
#' (\code{moran}, \code{geary}, or \code{getis-ord}=\code{go})
#' @param ymat Square matrix of observed values to be tested. If not given, will
#' be generated with specified values of \code{size} and \code{alpha}
#' @param seed Random seed
#'
#' @return Nothing (dumps statistics to screen)
#'
#' @seealso \code{test1d}, \code{test2d}
#'
#' @examples
#' \dontrun{
#' run_tests () # should give low p-values
#' run_tests (neutral=TRUE) # should give high p-values
#' }
#'
#' @export
run_tests <- function (size=10, alpha=c(0.1, 0.1), nt=100, ntests=100, 
                       neutral=FALSE, actype='moran', ymat, seed) 
{
    if (!missing (ymat))
    {
        if (!is.matrix (ymat)) stop ('ymat must be a matrix')
        if (dim (ymat) [1] != dim (ymat) [2]) stop ('ymat must be square')
    }

    if (missing (ymat))
    {
        if (neutral)
            fn <- 'neutral2d'
        else
            fn <- 'ives2D'
        if (missing (seed))
            ymat <- do.call (fn, list (nt=nt, sd=0.1, alpha=alpha))
        else
            ymat <- do.call (fn, list (nt=nt, sd=0.1, alpha=alpha, seed=seed))
    }
    size <- dim (ymat) [1]
    ydat <- sort ((ymat - min (ymat)) / diff (range (ymat)), decreasing=TRUE)

    actype <- tolower (actype)
    fn_ac <- NULL
    if (substring (actype, 1, 1) == 'g')
    {
        if (substring (actype, 3, 3) == 'a')
            fn_ac <- 'gearyc'
        else
            fn_ac <- 'getis_ord'
    } else
        fn_ac <- 'morani'
    mdat <- do.call (fn_ac, list (ymat))

    # To see how repeatable the tests are, they are performed with a different
    # seed
    set.seed (Sys.time ())
    
    cat ("\t|\t\tdifferences\tp-values\t|\t\t\t\t|\n", sep="")
    cat ("  dim\t|  alpha\traw\tAC\traw\tAC\t|\talpha\t\tn\t|\n", sep="")
    cat (rep ("-", 8), "|", rep ("-", 47), "|", rep ("-", 31), "|\n", sep="")
    alpha_s <- c (0.1, 0)
    for (i in 1:2)
    {
        t1 <- test1d (ymat, alpha=c(0.1, alpha_s [i]), ntests=ntests)
        ss_raw <- sum ((t1$data$raw - ydat) ^ 2)
        ss_ac <- sum ((t1$data$ac - mdat) ^ 2)
        cat ("  1\t|   (0.1, ", alpha_s [i], ")\t",
             formatC (ss_raw, format="f", digits=2), "\t",
             formatC (ss_ac, format="f", digits=2), "\t",
             formatC (t1$pvals$raw, format="f", digits=4), "\t",
             formatC (t1$pvals$ac, format="f", digits=4), "\t|   (",
             formatC (t1$pars$alpha [1], format="f", digits=2), ", ",
             formatC (t1$pars$alpha [2], format="f", digits=2), ")\t",
             round (t1$pars$n), "\t|\n", sep="")
    }

    alpha_t <- 0.1
    alpha_s <- c (0.1, 0)
    for (i in 1:2)
    {
        t2 <- test2d (ymat, alpha=c(alpha_t, alpha_s [i]), ntests=ntests)
        ss_raw <- sum ((t2$data$raw - ydat) ^ 2)
        ss_ac <- sum ((t2$data$ac - mdat) ^ 2)
        cat ("  2\t|   (0.1, ", alpha_s [i], ")\t",
             formatC (ss_raw, format="f", digits=2), "\t",
             formatC (ss_ac, format="f", digits=2), "\t",
             formatC (t2$pvals$raw, format="f", digits=4), "\t",
             formatC (t2$pvals$ac, format="f", digits=4), "\t|   (",
             formatC (t2$pars$alpha [1], format="f", digits=2), ", ",
             formatC (t2$pars$alpha [2], format="f", digits=2), ")\t",
             round (t2$pars$n), "\t|\n", sep="")
    }
    cat (rep ("-", 93), "\n", sep="")
}
