#' run_tests
#'
#' Tests observed data (\code{z}) against a series of neutral models
#'
#' @param nbs An \code{spdep} \code{nb} object listing all neighbours of each
#' point
#' @param alpha Vector of two components providing starting values for the
#' strength of autocorrelation in time and space
#' @param nt Number of successive layers of temporal and spatial autocorrelation
#' used to generate test field
#' @param ntests Number of tests to run, with statistics calculated from the
#' mean of \code{ntests}
#' @param neutral If TRUE, uses a neutral field for the tests rather than a
#' structured field generated by \code{ives2d}
#' @param ac_type type of autocorrelation statistic to use in tests
#' (\code{moran}, \code{geary}, or \code{getis-ord}=\code{go})
#' @param z Vector of observed values to be tested. If not given, will
#' be generated with specified values of \code{size} and \code{alpha}
#' @param seed Random seed
#'
#' @return Nothing (dumps statistics to screen)
#'
#' @seealso \code{test1d}, \code{test2d}
#'
#' @examples
#' \dontrun{
#' run_tests () # should give low p-values
#' run_tests (neutral=TRUE) # should give high p-values
#' }
#'
#' @export
run_tests <- function (nbs=nbs, alpha=c(0.1, 0.1), nt=100, ntests=100, 
                       neutral=FALSE, ac_type='moran', z, seed) 
{
    if (!missing (z))
    {
        if (length (z) != length (nbs))
            stop ('z must be same size as nbs')
    }

    if (missing (z))
    {
        dat <- ives2d (nt=nt, sd0=0.1, alpha=alpha)
        if (neutral)
            z <- rcpp_neutral2d (nbs=dat$nbs, alpha_t=alpha [1], 
                                 alpha_s=alpha[2], sd0=0.1, nt=nt)
        else
        {
            if (missing (seed))
                z <- dat$z
            else
                z <- ives2d (nt=nt, sd0=0.1, alpha=alpha, seed=seed)$z
        }
    }

    ac_type <- tolower (ac_type)
    if (substring (ac_type, 1, 1) == 'g')
    {
        if (substring (ac_type, 3, 3) == 'a')
            ac_type <- 'geary'
        else
            ac_type <- 'getis_ord'
    } else
        ac_type <- 'moran'

    ac <- rcpp_ac_stats (nbs, z, ac_type)
    zs <- sort ((z - min (z)) / diff (range (z)), decreasing=TRUE)

    # To see how repeatable the tests are, they are performed with a different
    # seed
    set.seed (Sys.time ())
    
    cat ("\t\tdifferences\tp-values\t|\t\t\t\t|\n", sep="")
    cat ("  alpha\t\traw\tAC\traw\tAC\t|\talpha\t\tn\t|\n", sep="")
    cat (rep ("-", 48), "|", rep ("-", 31), "|\n", sep="")

    alpha_t <- 0.1
    alpha_s <- c (0.1, 0)
    for (i in 1:2)
    {
        t2 <- test2d (z, nbs=nbs, alpha=c(alpha_t, alpha_s [i]), ntests=ntests)
        ss_raw <- 100 * sum ((t2$data$z - z) ^ 2) / length (nbs) ^ 2
        ss_ac <- 100 * sum ((t2$data$ac - ac) ^ 2) / length (nbs) ^ 2
        cat (" (0.1, ", alpha_s [i], ")\t",
             formatC (ss_raw, format="f", digits=2), "\t",
             formatC (ss_ac, format="f", digits=2), "\t",
             formatC (t2$pvals$raw, format="f", digits=4), "\t",
             formatC (t2$pvals$ac, format="f", digits=4), "\t|   (",
             formatC (t2$pars$alpha [1], format="f", digits=2), ", ",
             formatC (t2$pars$alpha [2], format="f", digits=2), ")\t",
             round (t2$pars$nt), "\t|\n", sep="")
    }
    cat (rep ("-", 80), "\n", sep="")
}
